%% Batch simulate

% Parameters
clear all;

% immutable
dt = 1*10^-4;
time = 6;
baseFrequency = 1;

synchronyLimit = 0.95;
timeTolerance = [-0.01, 0.01];

% variable
    % flock
numberOfIterations = 20;
frequencySpreads = 1.5;
phaseSpreads = 1;
flockRadi = 3; % Radius of spherical flock
flockDensities = 0.2; % Density of generated flock

    % flies
connectionThresholds = linspace(1,2.5,10); % Distance flys can see eachother

    % fly
zetas = 0.05; % fraction of period to go blind after seeing a flash
thaus = 0.05; % fraction of period to go blind after flashing


synchronyTime = zeros([ ...
    size(frequencySpreads, 2), ...
    size(phaseSpreads, 2), ...
    size(flockRadi, 2), ...
    size(flockDensities, 2), ...
    numberOfIterations, ... % ammount of simulations to average when stochastic variables are present
    size(connectionThresholds, 2), ...
    size(zetas, 2), ...
    size(thaus, 2), ...
    ]);

avgFlashesToSync = synchronyTime; % Make a copy of the empty matrix
averageSynchronyLevel = synchronyTime; % Again
averageConnections = synchronyTime; % Again



evaluations = prod(size(synchronyTime));    % Ammount of calculations needed
counter = 0;    % Keep track of calculations done
progressBar = waitbar(0, [num2str(counter), '/', num2str(evaluations)]);
tic; % Initialize update timer
for frequencySpreadIndex = 1:size(frequencySpreads, 2)
    frequencySpread = frequencySpreads(frequencySpreadIndex);
    for phaseSpreadIndex = 1:size(phaseSpreads, 2)
        phaseSpread = phaseSpreads(phaseSpreadIndex);
        for flockRadiusIndex = 1:size(flockRadi, 2)
            flockRadius = flockRadi(flockRadiusIndex);
            for flockDensityIndex = 1:size(flockDensities,2)
                flockDensity = flockDensities(flockDensityIndex);
                for iteration = 1:numberOfIterations
                    % Generate flock
                    Qinit = sphereFlock(flockRadius, flockDensity);
                    N = size(Qinit, 1);
                    Qinit(:,5) = phaseSpread*rand(N,1);
                    Qinit(:,6) = baseFrequency+frequencySpread*rand(N,1);
                    Qinit(:,7) = zeros(N,1);
                        
                    for connectionThresholdIndex = 1:size(connectionThresholds,2)
                        connectionThreshold = connectionThresholds(connectionThresholdIndex);
                        
                        [Q, G] = calculateGraph(Qinit, connectionThreshold);
                        
                        for zetaIndex = 1:size(zetas, 2)
                            zeta = zetas(zetaIndex);
                            for thauIndex = 1:size(thaus, 2)
                                thau = thaus(thauIndex);
                                
                                % Simulate
                                clear states; clear flashes; % Free up some memory
                                [states, flashes] = simulateFlock(Q, G, time, dt, thau, zeta);
                                
                                % evaluate
                                [synchronyTimeData, avgFlashesToSyncData, averageSynchronyLevelData ] = ...
                                evaluateSynchrony( states, flashes, dt, synchronyLimit, timeTolerance );
                                
                                % save result
                                synchronyTime( ...
                                    frequencySpreadIndex, ...
                                    phaseSpreadIndex, ...
                                    flockRadiusIndex, ...
                                    flockDensityIndex, ...
                                    iteration, ...
                                    connectionThresholdIndex, ...
                                    zetaIndex, ...
                                    thauIndex ...
                                    ) = synchronyTimeData;
                                    
                                avgFlashesToSync( ...
                                    frequencySpreadIndex, ...
                                    phaseSpreadIndex, ...
                                    flockRadiusIndex, ...
                                    flockDensityIndex, ...
                                    iteration, ...
                                    connectionThresholdIndex, ...
                                    zetaIndex, ...
                                    thauIndex ...
                                    ) = avgFlashesToSyncData;
                                
                                averageSynchronyLevel( ...
                                    frequencySpreadIndex, ...
                                    phaseSpreadIndex, ...
                                    flockRadiusIndex, ...
                                    flockDensityIndex, ...
                                    iteration, ...
                                    connectionThresholdIndex, ...
                                    zetaIndex, ...
                                    thauIndex ...
                                    ) = averageSynchronyLevelData;
                                   
                                averageConnections( ...
                                    frequencySpreadIndex, ...
                                    phaseSpreadIndex, ...
                                    flockRadiusIndex, ...
                                    flockDensityIndex, ...
                                    iteration, ...
                                    connectionThresholdIndex, ...
                                    zetaIndex, ...
                                    thauIndex ...
                                    ) = mean(degree(G));
                                
                                counter = counter + 1;
                                
                                if toc >= 1 % Update progress bar every second.
                                    waitbar(counter/evaluations, progressBar, [num2str(counter), '/', num2str(evaluations)]);
                                    tic;
                                end
                                
                            end
                        end
                    end
                end
            end
        end
    end
end
close(progressBar);
                                